name: Telegram Bot

on:
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyTelegramBotAPI

      - name: Run bot script
        run: |
          import telebot

          BOT_TOKEN = '8203812802:AAHf6qzWHlIPFws51lrUqkWVjth1_w9qTxA'
          YOUR_CHAT_ID = 1299749738

          bot = telebot.TeleBot(BOT_TOKEN)

          @bot.message_handler(commands=['start'])
          def handle_start(message):
              if message.chat.id == YOUR_CHAT_ID:
                  bot.send_message(message.chat.id, "سلام")
                  
          bot.polling()
